# Generated by Django 4.1.1 on 2022-10-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBookStore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
