# Generated by Django 4.1.1 on 2022-10-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBookStore', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
