# Generated by Django 4.1.1 on 2022-10-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBookStore', '0003_item_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomBookStore.item')),
                ('book_author', models.CharField(max_length=100)),
                ('book_isbn', models.CharField(max_length=100)),
            ],
        ),
    ]
