# Generated by Django 4.1.1 on 2022-10-25 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecomBookStore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecomBookStore', '0005_delete_book_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nameF', models.CharField(max_length=20)),
                ('nameL', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('cart', models.BooleanField(default=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.customer')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.customer_order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=20)),
                ('productDesc', models.CharField(max_length=300)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currentStock', models.PositiveIntegerField()),
                ('products', models.ManyToManyField(through='ecomBookStore.order_item', to='ecomBookStore.customer_order')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('productID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomBookStore.product')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('Author', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ratingScore', ecomBookStore.models.RangeIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=100)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.product')),
            ],
        ),
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('cardNumber', ecomBookStore.models.RangeBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('nameOnCard', models.CharField(max_length=20)),
                ('exprDate', models.DateField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order_item',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.product'),
        ),
        migrations.CreateModel(
            name='filter_tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=20)),
                ('products', models.ManyToManyField(to='ecomBookStore.product')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_address',
            fields=[
                ('deliveryID', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryAddress', models.CharField(max_length=50)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomBookStore.customer')),
            ],
        ),
    ]
