# Generated by Django 4.1.1 on 2022-11-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBookStore', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
