# Generated by Django 4.1.1 on 2022-11-01 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomBookStore', '0008_remove_delivery_address_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='customerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
