# Generated by Django 4.1.1 on 2022-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBookStore', '0011_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
